# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69305072a5e035716d6e34e126b46a7691449319b38995db458b41cb0dddb217b68b9ac708b84734e46d5921fa202338d9cc9861592354a59942e5170cfb4cc0

test:
  secret_key_base: a9ab6c253248aeeadb85c2598b6b9fffb969ee25417f4eb2bda8d4ea117474c071185434a1e5ebfd40d03435bc68b902405bc5b9b95f98ce23fdd419eb5c735a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
